# Generated by Django 5.1 on 2024-09-02 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_profiles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
